### ISSUE TITLE
bower-asset/imagesloaded not found

### ISSUE THREAD

**Issue by hlKittipan** [hiqdev/asset-packagist#155] opened 2023-04-24 09:33 UTC
Problem 1
    - The requested package bower-asset/imagesloaded could not be found in any version, there may be a typo in the package name.

**Comment by SilverFire** [comment] 2023-04-26 16:59
Works for me. Please, provide a way to reproduce a problem


```json
{
  "require": {
    "bower-asset/imagesloaded": "*"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
}
```

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking bower-asset/ev-emitter (v2.1.2)
  - Locking bower-asset/imagesloaded (v5.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading bower-asset/ev-emitter (v2.1.2)
  - Downloading bower-asset/imagesloaded (v5.0.0)
  - Installing bower-asset/ev-emitter (v2.1.2): Extracting archive
  - Installing bower-asset/imagesloaded (v5.0.0): Extracting archive
Generating autoload files
```

**Comment by SilverFire** [comment] 2023-04-26 17:00
Closing the issue for now, but as soon as you can provide a way to reproduce – it can be re-opened

**Closed by SilverFire** 2023-04-26 16:59 UTC
