### ISSUE TITLE
Search page shows newer version than detail page

### ISSUE THREAD

**Issue by holtkamp** [hiqdev/asset-packagist#163] opened 2023-11-02 11:50 UTC
_Might be related to https://github.com/hiqdev/asset-packagist/issues/156_

When searching on https://asset-packagist.org for datatables.net-buttons-bs on "any" platform, the URL becomes https://asset-packagist.org/package/search?query=datatables.net-buttons-bs&platform=bower%2Cnpm which shows:

![Screenshot 2023-11-02 at 12 39 41](https://github.com/hiqdev/asset-packagist/assets/776405/47b952a4-f788-4805-83d0-c3581e83ed7b)

As we can see for both NPM and Bower the most recent version is `2.4.2`.

When visiting the detail pages, we can see the following versions:
- NPM: 2.4.2 @ https://asset-packagist.org/package/detail?fullname=npm-asset/datatables.net-buttons-bs
![Screenshot 2023-11-02 at 12 46 03](https://github.com/hiqdev/asset-packagist/assets/776405/ad522de9-87e0-44b7-8248-35f05db94b69)

- Bower: 2.3.5 @ https://asset-packagist.org/package/detail?fullname=bower-asset/datatables.net-buttons-bs
![Screenshot 2023-11-02 at 12 46 39](https://github.com/hiqdev/asset-packagist/assets/776405/3f6f6bfd-d86d-4af9-b009-1625aa6b0378)

A few weeks ago the Bower variant was still also at `2.4.2`...

And when trying to install one of them, for NPM `2.3.6` is installed and for Bower version `2.3.5` is installed:

NPM
```json
{
	"require": {
		"npm-asset/datatables.net-buttons-bs": "^2.0"
	},
	"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	]
}
```

Bower:
```json
{
	"require": {
		"bower-asset/datatables.net-buttons-bs": "^2.0"
	},
	"repositories": [
		{
			"type": "composer",
			"url": "https://asset-packagist.org"
		}
	]
}
```

What could be the cause of this difference in used versions? 

When trying to force composer to download `^2.4`, the following errors are generated:

NPM
```Problem 1
    - Root composer.json requires npm-asset/datatables.net-buttons-bs ^2.4 -> satisfiable by npm-asset/datatables.net-buttons-bs[2.4.0, 2.4.1, 2.4.2].
    - npm-asset/datatables.net-buttons-bs[2.4.0, 2.4.1, 2.4.2] require npm-asset/datatables.net-buttons >=2.3.6 -> found npm-asset/datatables.net-buttons[dev-master, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5] but it does not match the constraint.
```

Bower:
```
Problem 1
    - Root composer.json requires bower-asset/datatables.net-buttons-bs ^2.4, found bower-asset/datatables.net-buttons-bs[dev-master, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5] but it does not match the constraint.
```

**Comment by SilverFire** [comment] 2023-11-02 14:29
Hi.
Thanks for a report, I will check it out next week

**Comment by FlorentTorregrosa** [comment] 2023-11-04 20:41
Hi,

I have the same problem for:

* https://asset-packagist.org/package/bower-asset/fontawesome: latest release 6.4.2, while on project page latest release is 6.3.0
* https://asset-packagist.org/package/bower-asset/bootstrap: latest release 5.3.1 (while it should be 5.3.2), while on project page latest release is 5.3.0-alpha1.

On Bower I obtain error on search page.

* https://bower.io/search/?q=bootstrap
* https://bower.io/search/?q=fontawesome

> Sorry, there was an error while fetching repositories

So I guess the problem is from Bower than asset-packagist?

The problem is that not all bower packages have the NPM equivalent.

**Comment by holtkamp** [comment] 2023-11-06 08:25
@FlorentTorregrosa thanks for the additional information!

>On Bower I obtain error on search page.

Yeah, that error has been there for months. Strange thing: "this" error we describe now, seems to be something of the last weeks... Maybe Bower's API has also shut down by now?

**Comment by acoesgarantem** [comment] 2023-11-10 12:22
Hi there, 

I have the same issue here, on asset-packagist.org is listing bower-asset/jquery 3.7.1 as last version.

But when we check the download page it's only available 3.6.4. It's breaking my Yii update. Can you check it please?

https://asset-packagist.org/package/bower-asset/jquery

Thanks.

**Comment by PlDevrie** [comment] 2024-07-23 09:12
I had a related issue on this page:
https://asset-packagist.org/package/bower-asset/bootstrap

today newest version is v5.3.3
yesterday it was v5.3.0-alpha1

I noticed it after a composer update, which downgraded 5.3.3 to 5.2.3, because 5.3.3 didn't seem to exist anymore.

**Comment by SilverFire** [comment] 2024-10-31 11:16
Seems to be related to the backend process, that fetches version lists.
When we render a search page, we fetch data from the Bower/NPM API without any caching, but the packages on the server are pre-fetched with a background worker.

From the links I see in this issue, I understand that it happens sometimes, but now it looks pretty consistent and I don't see anything in logs or monitoring that might give me an idea.

Closing the issue for now

**Closed** 2024-10-31 12:10 UTC

**Comment by holtkamp** [comment] 2024-11-05 19:16
Well, for my example it still applies...

https://asset-packagist.org/package/search?query=datatables.net-buttons-bs&platform=bower%2Cnpm

![Screenshot 2024-11-05 at 20 12 51](https://github.com/user-attachments/assets/ba2c5aed-7d15-4cf5-ab4a-953a18cb96bb)

Both version `3.1.2`

Detail pages: 

- NPM: 3.1.2 released on 30-08-2024, https://asset-packagist.org/package/detail?fullname=npm-asset/datatables.net-buttons-bs
- Bower: 3.1.0, released on 19-07-2024 https://asset-packagist.org/package/detail?fullname=bower-asset/datatables.net-buttons-bs
![Screenshot 2024-11-05 at 20 13 47](https://github.com/user-attachments/assets/b06a559d-c4ea-43d8-b4d0-00ab4845b36c)

![Screenshot 2024-11-05 at 20 13 53](https://github.com/user-attachments/assets/db07bafa-9f77-4f4e-92a8-7af4132bbd01)

https://github.com/DataTables/Dist-DataTables-Buttons-Bootstrap/releases
